Import('env')
env = env.Clone()
env.Append(CPPPATH=['#libs/cglm/include'])
env.ParseConfig('pkg-config sdl2 --cflags --libs')

conf = env.Configure()
if not conf.CheckLib('m'):
    print('Did not find libm.a or m.lib, exiting!')
    Exit(1)
env = conf.Finish()

env.Program('pong', [
    '#sdl2/sdl2.c',
    '#sdl2/engine.c',
    'main.c',
    'pong.c',
    'render.c',
    'utils.c',
    'player.c',
    'ball.c',
])
