Import('env')
env = env.Clone()
env.Append(CPPPATH=['#libs/cglm/include'])
env.ParseConfig('pkg-config sdl2 --cflags --libs')

conf = env.Configure()
if not conf.CheckLib('m'):
    print('Did not find libm.a or m.lib, exiting!')
    Exit(1)
env = conf.Finish()

env.Program('pong', [
    env.Object('pong-random', '#utils/random.cpp'),
    env.Object('pong-sdl2', '#sdl2/sdl2.c'),
    env.Object('pong-sdl2-engine', '#sdl2/engine.c'),
    'main.c',
    'pong.c',
    'action.c',
    'render.c',
    'utils.c',
    'player.c',
    'ball.c',
    'wall.c',
    'midfield.c',
])
